# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: portfolio-db
    image: mysql:5.7
    build: ./
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: selfintroapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass4649
      TZ: Asia/Tokyo
    ports:
        3306
    hostname: selfintroapp