
spring:
  datasource:
    url: jdbc:mysql://db-java-portfolio-01.c9g8ky3xvz4n.ap-northeast-1.rds.amazonaws.com:3306/selfintroapp
    username: admin
    password: Pass4649
    driver-class-name: com.mysql.cj.jdbc.Driver  
    
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  thymeleaf:
    prefix: file:src/main/resources/templates/


spring.mvc.hiddenmethod.filter.enabled: true
mybatis:
  mapper-locations: classpath*:/src/main/resources/com/example/selfintroapp/mapper/SelfintroAppMapper.xml

server:
    port: 58080