
spring:
  datasource:
    url: jdbc:mysql://db-java-portfolio-01.c9g8ky3xvz4n.ap-northeast-1.rds.amazonaws.com:3306/selfintroapp
    username: admin
    password: Pass4649
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
    
    
    
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  thymeleaf:
    prefix: file:src/main/resources/templates/

cloud:
  aws:
    stack:
      # CloudFormationのstack名を自動収集しない
      auto: false
    region:
      # EC2のmetadataを自動収集しない
      auto: false
      static: ap-northeast-1

spring.mvc.hiddenmethod.filter.enabled: true
spring.mvc.log-request-details: true

logging:
  level:
    root: DEBUG
    

server:
    port: 58080