
spring:
  datasource:
    url: jdbc:mysql://db-java-portfolio-01.c9g8ky3xvz4n.ap-northeast-1.rds.amazonaws.com:3306/selfintroapp
    username: admin
    password: pass4649
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  thymeleaf:
    prefix: file:src/main/resources/templates/
cloud:
  aws:
    stack:
      # CloudFormationのスタック名を自動取得しない
      auto: false
    region:
      # リージョン名を自動取得しない
      auto: false
      # リージョン名（例. ap-northeast-1）
      static: ap-northeast-1      

spring.mvc.hiddenmethod.filter.enabled: true

server:
    port: 58080